<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: sans-serif; font-size: 11px; color: #1a1a1a; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 3px solid #1E2A78; padding-bottom: 12px; }
        .header h1 { color: #1E2A78; font-size: 18px; margin: 0 0 4px 0; }
        .header p { margin: 2px 0; color: #444; font-size: 11px; }
        .meta-table { width: 100%; margin-bottom: 20px; border-collapse: collapse; }
        .meta-table td { padding: 3px 6px; font-size: 10px; }
        .meta-table td.label { font-weight: bold; color: #1E2A78; width: 120px; }
        table.entries { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.entries th { background: #1E2A78; color: #fff; padding: 6px; text-align: left; font-size: 10px; }
        table.entries td { border-bottom: 1px solid #ddd; padding: 6px; vertical-align: top; font-size: 10px; }
        .status { font-size: 9px; padding: 2px 6px; border-radius: 8px; }
        .status-draft { background: #e2e8f0; color: #475569; }
        .status-submitted { background: #ffe8cc; color: #b45309; }
        .status-reviewed { background: #cceff3; color: #0e7490; }
        .footer { margin-top: 20px; font-size: 9px; color: #888; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Busitema University &mdash; Faculty of Engineering</h1>
        <p>Internship Logbook</p>
    </div>

    <table class="meta-table">
        <tr>
            <td class="label">Student</td>
            <td>{{ $student->name }}</td>
            <td class="label">Company</td>
            <td>{{ $internship->company_name }}</td>
        </tr>
        <tr>
            <td class="label">Department</td>
            <td>{{ optional($internship->department)->name ?? 'N/A' }}</td>
            <td class="label">Year of Study</td>
            <td>{{ $internship->year_of_study }}</td>
        </tr>
        <tr>
            <td class="label">Generated</td>
            <td colspan="3">{{ now()->format('l, d F Y') }}</td>
        </tr>
    </table>

    <table class="entries">
        <thead>
            <tr>
                <th style="width: 10%">Date</th>
                <th style="width: 25%">Operations Carried Out</th>
                <th style="width: 18%">Tools/Equipment</th>
                <th style="width: 15%">Challenges</th>
                <th style="width: 15%">Recommendations</th>
                <th style="width: 10%">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($entries as $entry)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($entry->date)->format('d M Y') }}</td>
                    <td>{{ $entry->operations_carried_out }}</td>
                    <td>{{ $entry->tools_equipment_used }}</td>
                    <td>{{ $entry->challenges_faced ?? '—' }}</td>
                    <td>{{ $entry->recommendations ?? '—' }}</td>
                    <td>
                        <span class="status status-{{ $entry->status }}">
                            {{ ucfirst($entry->status) }}
                        </span>
                    </td>
                </tr>
            @empty
                <tr><td colspan="6">No entries found for the selected period.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by BU E-Logbook on {{ now()->format('d M Y, H:i') }}
    </div>
</body>
</html>